[versions]
mod = "0.0.1"
fabric-loader = "0.19.3"
fabric-api-v12111 = "0.141.6+1.21.11"
fabric-loom = "1.17-SNAPSHOT"
minecraft-v12111 = "1.21.11"
byte-buddy = "1.18.11"
graal = "25.1.3"
gson = "2.13.2"
jetbrains-annotations = "26.0.2"
junit = "6.1.2"
palantir-java-format = "2.97.0"
qodana-gradle-plugin = "2026.2.0"
slf4j = "2.0.7"
sonarqube-gradle-plugin = "7.3.1.8318"
spotless = "8.8.0"

[libraries]
fabric-api-v12111 = { module = "net.fabricmc.fabric-api:fabric-api", version.ref = "fabric-api-v12111" }
fabric-loader = { module = "net.fabricmc:fabric-loader", version.ref = "fabric-loader" }
minecraft-v12111 = { module = "com.mojang:minecraft", version.ref = "minecraft-v12111" }
bytebuddy-core = { module = "net.bytebuddy:byte-buddy", version.ref = "byte-buddy" }
graal-collections = { module = "org.graalvm.sdk:collections", version.ref = "graal" }
graal-jniutils = { module = "org.graalvm.sdk:jniutils", version.ref = "graal" }
graal-js-core = { module = "org.graalvm.js:js", version.ref = "graal" }
graal-js-language = { module = "org.graalvm.js:js-language", version.ref = "graal" }
graal-nativeimage = { module = "org.graalvm.sdk:nativeimage", version.ref = "graal" }
graal-polyglot = { module = "org.graalvm.polyglot:polyglot", version.ref = "graal" }
graal-regex = { module = "org.graalvm.regex:regex", version.ref = "graal" }
graal-shadowed-icu4j = { module = "org.graalvm.shadowed:icu4j", version.ref = "graal" }
graal-shadowed-xz = { module = "org.graalvm.shadowed:xz", version.ref = "graal" }
graal-truffle-api = { module = "org.graalvm.truffle:truffle-api", version.ref = "graal" }
graal-word = { module = "org.graalvm.sdk:word", version.ref = "graal" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit" }
slf4j-api = { module = "org.slf4j:slf4j-api", version.ref = "slf4j" }
sonarqube-gradle-plugin = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version.ref = "sonarqube-gradle-plugin" }

[plugins]
fabric-loom-remap = { id = "net.fabricmc.fabric-loom-remap", version.ref = "fabric-loom" }
qodana = { id = "org.jetbrains.qodana", version.ref = "qodana-gradle-plugin" }
spotless = { id = "com.diffplug.spotless", version.ref = "spotless" }
