/*
 * My QOL Scripts - A powerful scripting mod for Minecraft.
 * Copyright (C) 2026 Titouan Réthoré
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program. If not, see <https://www.gnu.org/licenses/>.
 */

package net.me.scripting.typings;

import net.me.Main;
import net.me.scripting.mappings.MappingsManager;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * Generates TypeScript declaration files (.d.ts) for the My QOL Scripts API and Minecraft mappings.
 * <p>
 * This class relies on the {@link MappingsManager} to retrieve the necessary mappings data and uses
 * the {@link MqsApiDtsEmitter} and {@link MinecraftMappingsDtsEmitter} to generate the appropriate TypeScript
 * declarations. The generated file is saved myqolscripts/scripts/mqs.d.ts.
 */
public class TypeDefinitionGenerator {
    private static final Path OUTPUT_DIRECTORY = Main.MOD_DIR.resolve("scripts");
    private static final String OUTPUT_FILE_NAME = "mqs.d.ts";

    private final MappingsManager mappingsManager;
    private final MqsApiDtsEmitter mqsApiDtsEmitter;
    private final MinecraftMappingsDtsEmitter minecraftMappingsDtsEmitter;

    public TypeDefinitionGenerator(MappingsManager mappingsManager) {
        this.mappingsManager = mappingsManager;
        this.mqsApiDtsEmitter = new MqsApiDtsEmitter();
        this.minecraftMappingsDtsEmitter = new MinecraftMappingsDtsEmitter();
    }

    public boolean isReady() {
        return mappingsManager.isReady();
    }

    public GenerationResult generate() throws IOException {
        if (!isReady()) {
            throw new IllegalStateException("Mappings are not ready yet.");
        }

        Map<String, String> sortedClassMap = new TreeMap<>(mappingsManager.getClassMap());
        Map<String, Map<String, List<String>>> methodMap = mappingsManager.getMethodMap();
        Map<String, Map<String, String>> fieldMap = mappingsManager.getFieldMap();

        StringBuilder builder = new StringBuilder(2_000_000);
        appendHeader(builder, sortedClassMap.size());
        mqsApiDtsEmitter.append(builder);
        minecraftMappingsDtsEmitter.append(builder, sortedClassMap.keySet(), methodMap, fieldMap);

        Files.createDirectories(OUTPUT_DIRECTORY);
        Path outputPath = OUTPUT_DIRECTORY.resolve(OUTPUT_FILE_NAME);
        Files.writeString(
                outputPath,
                builder.toString(),
                StandardCharsets.UTF_8,
                StandardOpenOption.CREATE,
                StandardOpenOption.TRUNCATE_EXISTING,
                StandardOpenOption.WRITE
        );

        int methodCount = methodMap.values().stream().mapToInt(Map::size).sum();
        int fieldCount = fieldMap.values().stream().mapToInt(Map::size).sum();

        return new GenerationResult(outputPath, sortedClassMap.size(), methodCount, fieldCount);
    }

    private void appendHeader(StringBuilder builder, int classCount) {
        builder.append("// Auto-generated by /mqs generate\n");
        builder.append("// File: ").append(OUTPUT_FILE_NAME).append("\n");
        builder.append("// Minecraft mapped classes: ").append(classCount).append("\n\n");
    }

    public record GenerationResult(Path outputPath, int classCount, int methodCount, int fieldCount) {
    }
}
